---
title: Jack Sleight
page-layout: full
format:
    typst:
        template-partials:
            - typst-template.typ
    html:
        toc: true
        toc_depth: 3
        toc_float: true
        toc_smooth_scroll: true
        toc_highlight: true
        fig-align: center
---

## Summary

I am an R developer and data scientist with over 6 years of experience. My
current role as R/R Shiny developer at Audit Scotland involves acting as a lead
developer for the design and maintenance of web-based data applications. These
are used by a team of auditors for the analysis of financial and performance
audit data generated by public sector organisations in Scotland. In my previous
role at Fios Genomics I acted as a lead bioinformatic data scientist providing
statistical analyses for a range of clients in the pharmaceutical and academic
sectors. I have acquired transferable skills and experiences from both the
private life science and public audit sectors in analysing complex data sets and
developing data-centred products.

## Skills

:::: {layout-ncol="2"}

::: {.column width="50%"}
### Programming
- R
- Python
- SQL
- JavaScript
- Bash
:::

::: {.column width="50%"}
### Bioinformatics
- DNA/RNA sequencing
- ASO design
- Proteomics
- High-throughput screening development
:::

::::

:::: {layout-ncol="2"}

::: {.column width="50%"}
### Data science
- Tidyverse/Tidymodels
- Quarto/RMarkdown
- Shiny/Plotly
- Numpy/Pandas/Matplotlib/Seabor
:::

::: {.column width="50%"}
### Engineering
- Git
- Docker
- CI/CD
- NextFlow
- Linux
- Azure
- Relational database design
:::

::::

## Experience

### Audit Scotland, Glasgow

::: {.content-visible when-format="html"}
#### R/R Shiny Developer<span style="float: right;">2025-Present
:::
```{=typst}
#justified_header("R/R Shiny Developer", "2025-Present")
```

- I design and maintain web-based data applications using R, SQL and Python that
are used by teams of financial and performance auditors to perform a range of
analyses. Typical analyses include but are not limited to:
    - Analysis of general ledger and financial statement data.
    - Collation of Audit Scotland parliamentary interaction data.
- I design and maintain data pipelines for extracting, transforming and loading
public sector data into structured and semi-structured data sets such as
relational databases or JSON file stores, respectively.
- I use Git for version control and develop GitHub pipelines for maintaining
code and adhering to continuous integration (CI) and continuous development (CD)
practices.
- I am involved in the maintenance of Microsoft Azure services for hosting
web-based applications.
I lead the development of best practice guidance documentation for R programming
at Audit Scotland.

### Fios Genomics, Edinburgh

::: {.content-visible when-format="html"}
#### Senior Bioinformatics Developer<span style="float: right;">2023-2025
:::
```{=typst}
#justified_header("Senior Bioinformatics Developer", "2023-2025")
```
- I contributed to an internal codebase using R, SQL, Python and JavaScript that
was used by a team of bioinformaticians. Typical analyses included but were not
limited to:
    - Critical and confounding factors analysis biological experimental study
    designs.
    - Analysis of high dimenstional data such as gene expression, proteomic or
    custom array data sets.
    - Hypergeometric and gene-set enrichment testing of biological pathways.
    - Designing personalised allele-specific anti-sense oligonucleotide (ASO).
    - Data mining of public bioinformatic databases.
    - Development of machine learning models for predicting patient drug response
    using omics data.
- I was involved in the communication of code updates and new features via blog
posts and presentations.
- I was responsible for ensuring reproducibility of statistical analyses using
tools such as Docker and GitLab CI pipelines.

::: {.content-visible when-format="html"}
#### Senior Bioinformatician<span style="float: right;">2021-2023
:::
```{=typst}
#justified_header("Senior Bioinformatician", "2021-2023")
```
- I acted as a lead bioinformatic data scientist for a range of different
statistical analysis projects.
- I provided scientific and technical guidance to junior bioinformaticians.
- I was regularly involved in scoping statistical analysis plans for new and
existing clients.

::: {.content-visible when-format="html"}
#### Bioinformatician<span style="float: right;">2021-2023
:::
```{=typst}
#justified_header("Bioinformatician", "2019-2021")
```
- I acted as a junior bioinformatic data scientist, performing statistical
analyses for clients in the pharmaceutical and academic sectors.

### Cancer Research UK Scotland Institute, Glasgow

::: {.content-visible when-format="html"}
#### Laboratory Aide<span style="float: right;">2015-2016
:::
```{=typst}
#justified_header("Laboratory Aide", "2015-2016")
```
- I was part of a large team responsbile for preparation of tissue culture
solutions and autoclaving of laboratory waste.

## Education

### University of Glasgow

::: {.content-visible when-format="html"}
#### Master of Science - Bioinformatics with Distinction with Distinction<span style="float: right;">2018-2019
:::
```{=typst}
#justified_header("Master of Science - Bioinformatics with Distinction with Distinction", "2018-2019")
```
- I was awarded a Scottish Funding Council scholarship based on undergraduate
academic performance.

### University of Strathclyde

::: {.content-visible when-format="html"}
#### Bachelor of Science - Pharmacology and Biochemistry with First Class Honours<span style="float: right;">2016-2018
:::
```{=typst}
#justified_header("Bachelor of Science - Pharmacology and Biochemistry with First Class Honours", "2016-2018")
```
- I was awarded the Biochemical Society prize for academic achievement.

### University of Glasgow

::: {.content-visible when-format="html"}
#### Diploma of Higher Education - Medical Science<span style="float: right;">2013-2015
:::
```{=typst}
#justified_header("Diploma of Higher Education - Medical Science", "2013-2015")
```

## Training and teaching
- 2025 – I attended the Shiny in Production conference run by Jumping Rivers Ltd.
- 2022 – I completed the Exploring Genetic Variation EMBI-EBL virtual course.
- 2021 – I presented a COVID-19 R Shiny application at the Edinburgh Data
Visualisation Meetup
- 2019 – I participated in a study group on “Introduction to Statistical Learning”
by James et. al.

